MOHomeCareApp/Controllers/DuesController.cs
using MOHomeCareApp.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MOHomeCareApp.Controllers
{
    [Authorize(Roles = "User")]
    public class DuesController : Controller
    {
        // GET: Dues
        public ActionResult Index()
        {
            DataSet dsFilesAvailable;
            File files = new File();
            
            dsFilesAvailable = files.GetFilesInFolder();
            files.InsertUploadsAvailables(dsFilesAvailable);
            ViewBag.UploadsAvailable = files.GetListOfFilesToProcess();
            return View();
        }

        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            File files = new File();
            ViewBag.UploadsAvailable = files.UpdateFileProcessHistory(form);
            files.DumpFileInformationToDataSet(form);
            return View();
        }

        public ActionResult FileProcessingResults()
        {

            return View();
        }

    }
}

MOHomeCareApp/Controllers/WorkersController.cs
using MOHomeCareApp.Models;
using MOHomeCareApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MOHomeCareApp.Controllers
{
    [Authorize(Roles = "User")]
    public class WorkersController : Controller
    {
        [HttpGet]
        public ActionResult WorkerSummary(int id, string window)
        {
            WorkerSummaryReport model = new WorkerSummaryReport();
            Worker w = new Worker();
            
            if (window == "_global")
            {
                model = w.WorkerListGlobalInformation(id);
                model.windowsOption = "Global";
            }
            if (window == "_address")
            {
                model = w.WorkerListAddressInformation(id);
                model.windowsOption = "Address";
            }
            if (window == "_phone")
            {
                model = w.WorkerListPhoneInformation(id);
                model.windowsOption = "Phone";
            }
            if (window == "_email")
            {
                model = w.WorkerListEmailInformation(id);
                model.windowsOption = "Email";
            }
            if (window == "_language")
            {
                model = w.WorkerListLanguageInformation(id);
                model.windowsOption = "Language";
            }

            model.windowView = window;
            model.WorkerId = id;

            return View(model);
        }

        public ActionResult SearchResults()
        {
            try
            {
                WorkerSearchResult model = new WorkerSearchResult();
                model.searchResults = (List<SearchWorkers_Result>)TempData["resList"];
                if(model.searchResults.Any())
                {
                    return View(model);
                }
                return RedirectToRoute("Search");
            }
            catch(Exception ex)
            {
                ex.ToString();
                return RedirectToRoute("Search");
            }     
        }

        public ActionResult Search()
        {
            WorkerSearch model = new WorkerSearch();
            return View(model);
        }

        [HttpPost]
        public ActionResult Search(WorkerSearch form)
        {
            Worker w = new Worker();
            var resList = w.SearchWorker(form);
            if(resList.Count() > 0)
            {
                TempData["resList"] = resList;
                return RedirectToRoute("SearchResults");
            }
            else
            return View(form);
        }

        // GET: Workers
        public ActionResult Index()
        {
            Contacts cn = new Contacts();
            Addresses ad = new Addresses();
            var langList = cn.getAllLanguages();
            WorkerDataEntry model  = new WorkerDataEntry();
            model.vmHomeLanguage = new SelectList(cn.getAllLanguages(), "vmHomeLanguageName", "vmHomeLanguageId");
            model.vmHomeState = new SelectList(ad.getSelectListOfStates(), "vmHomeStateId", "vmHomeStateName");
            model.vmMailState = new SelectList(ad.getSelectListOfStates(), "vmHomeStateId", "vmHomeStateName");
            model.vmUnionSigned = new SelectList(cn.getListOfYesAndNo(), "Value", "Text");
            model.vmCareSigned = new SelectList(cn.getListOfYesAndNo(), "Value", "Text");
            model.vmDataSource = new SelectList(cn.getCardSources(), "vmDataSourceId", "vmDataSourceName");
            return View(model);
        }

        [HttpPost]
        public ActionResult Index (WorkerDataEntry form)
        {
            Addresses ad = new Addresses();
            Contacts cn = new Contacts();
            WorkerDataEntry model = new WorkerDataEntry();
            form.vmHomeLanguage = new SelectList(cn.getAllLanguages(), "vmHomeLanguageName", "vmHomeLanguageId");
            form.vmHomeState = new SelectList(ad.getSelectListOfStates(), "vmHomeStateId", "vmHomeStateName");
            form.vmMailState = new SelectList(ad.getSelectListOfStates(), "vmHomeStateId", "vmHomeStateName");
            form.vmUnionSigned = new SelectList(cn.getListOfYesAndNo(), "Value", "Text");
            form.vmCareSigned = new SelectList(cn.getListOfYesAndNo(), "Value", "Text");
            form.vmDataSource = new SelectList(cn.getCardSources(), "vmDataSourceId", "vmDataSourceName");

            if (ModelState.IsValid)
            {
                Worker w = new Worker();
                w.InsertNewWorker(form);
                return View(form);
            }
            return View(form);
        }

        [HttpGet]
        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult GetListOfCities(string term)
        {
            Addresses a = new Addresses();
            var cities = a.getAllCities(term);
            return Json(cities.Select(t => new { id = t.vmHomeCityId, value = t.vmHomeCity, label = t.vmHomeCity }), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult GetListOfZips(string term)
        {
            Addresses a = new Addresses();
            var zips = a.getAllZips(term);
            return Json(zips.Select(t => new { id = t.zipId, value = t.zipId, label = t.zipId }), JsonRequestBehavior.AllowGet);
        }
    }
}

MOHomeCareApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AFSCME</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/jqueryiucss")
    @Styles.Render("~/Admin/styles")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AFSCME", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
            @if (Request.IsAuthenticated)
            {
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">Dues<b class="caret"></b></a>
                        <ul role="menu" class="dropdown-menu">
                            <li>@Html.ActionLink("File Processing", "Index", "Dues")</li>
                        </ul>
                    </li>
                    <li>
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">Workers<b class="caret"></b></a>
                        <ul role="menu" class="dropdown-menu">
                            <li>@Html.ActionLink("Entry", "Index", "Workers")</li>
                            <li>@Html.ActionLink("Search", "Search", "Workers")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Reports", "About", "Home")</li>
                    <li>@Html.ActionLink("Worker Activity", "About", "Home")</li>
                </ul>
            }

            @if (Request.IsAuthenticated)
            {
                @Html.Partial("_LoginPartial")
            }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AFSCME Applications</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryiu")
    @Scripts.Render("~/admin/scripts")
    @RenderSection("scripts", required: false)
    
    <form class="hidden" id="anti-forgery-form">
        @Html.AntiForgeryToken()
    </form>

</body>
</html>